// Code generated by counterfeiter. DO NOT EDIT.
package commandfakes

import (
	"sync"

	"github.com/juliencherry/envs/command"
)

type FakeStateManager struct {
	GetEnvsStub        func() ([]string, error)
	getEnvsMutex       sync.RWMutex
	getEnvsArgsForCall []struct{}
	getEnvsReturns     struct {
		result1 []string
		result2 error
	}
	getEnvsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	SaveEnvStub        func(env string) error
	saveEnvMutex       sync.RWMutex
	saveEnvArgsForCall []struct {
		env string
	}
	saveEnvReturns struct {
		result1 error
	}
	saveEnvReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStateManager) GetEnvs() ([]string, error) {
	fake.getEnvsMutex.Lock()
	ret, specificReturn := fake.getEnvsReturnsOnCall[len(fake.getEnvsArgsForCall)]
	fake.getEnvsArgsForCall = append(fake.getEnvsArgsForCall, struct{}{})
	fake.recordInvocation("GetEnvs", []interface{}{})
	fake.getEnvsMutex.Unlock()
	if fake.GetEnvsStub != nil {
		return fake.GetEnvsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getEnvsReturns.result1, fake.getEnvsReturns.result2
}

func (fake *FakeStateManager) GetEnvsCallCount() int {
	fake.getEnvsMutex.RLock()
	defer fake.getEnvsMutex.RUnlock()
	return len(fake.getEnvsArgsForCall)
}

func (fake *FakeStateManager) GetEnvsReturns(result1 []string, result2 error) {
	fake.GetEnvsStub = nil
	fake.getEnvsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeStateManager) GetEnvsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.GetEnvsStub = nil
	if fake.getEnvsReturnsOnCall == nil {
		fake.getEnvsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getEnvsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeStateManager) SaveEnv(env string) error {
	fake.saveEnvMutex.Lock()
	ret, specificReturn := fake.saveEnvReturnsOnCall[len(fake.saveEnvArgsForCall)]
	fake.saveEnvArgsForCall = append(fake.saveEnvArgsForCall, struct {
		env string
	}{env})
	fake.recordInvocation("SaveEnv", []interface{}{env})
	fake.saveEnvMutex.Unlock()
	if fake.SaveEnvStub != nil {
		return fake.SaveEnvStub(env)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.saveEnvReturns.result1
}

func (fake *FakeStateManager) SaveEnvCallCount() int {
	fake.saveEnvMutex.RLock()
	defer fake.saveEnvMutex.RUnlock()
	return len(fake.saveEnvArgsForCall)
}

func (fake *FakeStateManager) SaveEnvArgsForCall(i int) string {
	fake.saveEnvMutex.RLock()
	defer fake.saveEnvMutex.RUnlock()
	return fake.saveEnvArgsForCall[i].env
}

func (fake *FakeStateManager) SaveEnvReturns(result1 error) {
	fake.SaveEnvStub = nil
	fake.saveEnvReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStateManager) SaveEnvReturnsOnCall(i int, result1 error) {
	fake.SaveEnvStub = nil
	if fake.saveEnvReturnsOnCall == nil {
		fake.saveEnvReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveEnvReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStateManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getEnvsMutex.RLock()
	defer fake.getEnvsMutex.RUnlock()
	fake.saveEnvMutex.RLock()
	defer fake.saveEnvMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStateManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ command.StateManager = new(FakeStateManager)
